### ISSUE TITLE
Integration with GeoLite2 DB

### ISSUE THREAD

**Issue by chwagssd** [bluesmoon/node-geoip#137]
Looks like GeoLite2 will be all that's available starting **January 2, 2019**

Would be good to verify that integration supports the GeoLite2 DB format as that approaches.

**Comment by bluesmoon** [comment]
If anyone's willing to do the verification and make any required code changes, I'll be happy to merge it in, however I don't have the time to do this myself.

**Comment by ar2rsawseen** [comment]
@bluesmoon my attempt is here (https://github.com/bluesmoon/node-geoip/pull/138), please review :)

**Comment by Gourmentt** [comment]
@bluesmoon as far as I can see you've updated the lib but didn't updated npm lib, it still contains 1.2.2:
https://www.npmjs.com/package/geoip-lite.

please publish it

**Comment by bluesmoon** [comment]
done

**Comment by Gourmentt** [comment]
@bluesmoon thank you but you forgot to update bases inside /data folder, could you do that?

**Comment by ar2rsawseen** [comment]
I think my PR provided updated files, so they should be in repo, so should automatically go to npm too, no?

**Comment by Gourmentt** [comment]
I don't know, I just installed it from scratch and for example IP 31.13.189.169 not resolved by lib. But after update databases it resolves correctly, so I consider it as prove that databases still outdated in npm package.

**Comment by ar2rsawseen** [comment]
I think you are partially right and it is my fault. I think I did not include the latest build, let me rebuild it and check

**Comment by ar2rsawseen** [comment]
Added them here:
https://github.com/bluesmoon/node-geoip/pull/140

**Comment by Gourmentt** [comment]
@ar2rsawseen thanks, ping me when it will be built and published
